/**
 * @file encoder_motor.c
 * @author Lu Yongping (Lucas@hiwonder.com)
 * @brief Encoder motor hardware independent code
 * @version 0.1
 * @date 2023-07-12
 *
 * @copyright Copyright (c) 2023
 *
 */


#include "encoder_motor.h"

/**
 * @brief Encoder motor speed measurement update
 * @detials
 * @param self Encoder motor object pointer
 * @param period The time interval between the current update and the last update (update cycle), unit: sec
 * @param counter Current count value of the encoder
 * @retval None.
*/
void encoder_update(EncoderMotorObjectTypeDef *self, float period, int64_t counter)
{
    counter = counter + self->overflow_num * self->ticks_overflow; /* Total count value, 60000 according to the actual set timer overflow value */
    int delta_count = counter - self->counter;
    self->counter = counter; /* Store the new count value */
    self->tps = (float)delta_count / period * 0.9f + self->tps * 0.1f; /* Calculate pulse frequency */
    self->rps = self->tps / self->ticks_per_circle; /* Calculate the speed in rps, revolutions per second */
}

/**
 * @brief Encoder motor speed control task
 * @detials Encoder motor speed PID control task, requires timing to complete PID control update
 * @param self Encoder motor object pointer
 * @param period The time interval between the current update and the last update (update cycle), unit: sec
 * @retval None.
*/
void encoder_motor_control(EncoderMotorObjectTypeDef *self, float period) 
{
	float pulse = 0;
    pid_controller_update(&self->pid_controller, self->rps, period);   /* Update PID Controller */
    pulse = self->current_pulse + self->pid_controller.output; /* Calculate new PWM value */
	
	/* Limit the output PWM value. The limit is determined by the timer setting. In this example,
       the duty cycle of the timer setting is 0-100, which corresponds to 0-1000. 
    */
    pulse = pulse > 1000 ?  1000 : pulse; 
    pulse = pulse < -1000 ? -1000 : pulse;
	
    /* Set a new PWM value and limit the minimum PWM value. If the PWM is too small,
       the motor will only make a buzzing sound but not move.
    */
    self->set_pulse(self, pulse > -250 && pulse < 250 ? 0 : pulse);
    self->current_pulse = pulse; /* Record the new PWM value */
}


/**
 * @brief Encoder motor sets PID control target speed
 * @param self Encoder motor object pointer
 * @param rps Target speed, in revolutions per second
 * @retval None.
 */
void encoder_motor_set_speed(EncoderMotorObjectTypeDef *self, float rps)
{
	rps = rps > self->rps_limit ? self->rps_limit : (rps < -self->rps_limit ? -self->rps_limit : rps); /* Limit the speed */
    self->pid_controller.set_point = rps; /* Setting the PID Controller Target */
}

/**
 * @breif Encoder motor object initialization
 * @param self Encoder motor object pointer
 * @retval None.
*/
void encoder_motor_object_init(EncoderMotorObjectTypeDef *self)
{
    self->counter = 0;
    self->overflow_num = 0;
    self->tps = 0; 
    self->rps = 0;
	self->current_pulse = 0;
	self->ticks_overflow = 0;
    
    /* The number of counts generated by one rotation of the motor output shaft.
       Fill in according to the actual situation of the motor. 
    */
    self->ticks_per_circle = 9999;
	pid_controller_init(&self->pid_controller, 0, 0, 0);
}

