/**
 * @file encoder_motor.h
 * @author Lu Yongping (Lucas@hiwonder.com)
 * @brief 编码器电机控制头文件
 * @version 0.1
 * @date 2023-05-12
 *
 * @copyright Copyright (c) 2023
 *
 */

#ifndef __ENCODER_MOTOR_H_
#define __ENCODER_MOTOR_H_

#include <stdint.h>
#include "pid.h"

typedef struct EncoderMotorObject EncoderMotorObjectTypeDef;

/**
 * @brief Encoder motor object structure
*/
struct EncoderMotorObject{
    int64_t counter;        /**< @brief Total value, 64bit is assumed to not overflow */
    int64_t overflow_num;   /**< @brief Overflow count */
    int32_t ticks_overflow; /**< @brief Count overflow value */
    float tps;              /**< @brief ticks per second Counter frequency */
    float rps;              /**< @brief revolutions per second Output shaft speed RPM */
    int current_pulse;      /**< @brief The current output PWM value, the sign corresponds to the positive and negative */
    PID_ControllerTypeDef pid_controller; /**< @brief PID Controller */

    // porting Portable Hardware Interface
    /** 
     * @brief The number of counts generated by one rotation of the motor output shaft.
     * Fill in according to the actual situation of the motor.
    */
    int32_t ticks_per_circle;
    /** 
     * @brief The motor speed limit is usually slightly lower than the speed at 100% PWM
     * duty cycle to ensure the PID controller can control the speed.
    */
	float rps_limit;
    /**
     * @brief Setting the Motor Speed  -1000 ~ 1000
     * @param self Encoder Motor Object
     * @param pulse The new PWM value, -1000~1000, corresponds to 0~100% speed in forward and reverse rotation
     * @retval None.
    */
    void (*set_pulse)(EncoderMotorObjectTypeDef *self, int pulse);
};


/**
 * @breif Encoder motor object initialization
 * @param self Encoder motor object pointer
 * @retval None.
*/
void encoder_motor_object_init(EncoderMotorObjectTypeDef *self);


/**
 * @brief Encoder motor speed measurement update
 * @detials
 * @param self Encoder Motor Object
 * @param period The time interval between this call and the last call, in seconds
 * @param counter Current count value of the encoder
 * @retval None.
*/
void encoder_update(EncoderMotorObjectTypeDef *self, float period, int64_t new_counter);


/**
 * @brief Encoder motor speed control task
 * @detials Encoder motor speed PID control task, requires timing specification to complete PID control update
 * @param self Encoder Motor Object
 * @param period The time interval between the current update and the last update (update cycle), unit: sec
 * @retval None.
*/
void encoder_motor_control(EncoderMotorObjectTypeDef *self, float period);


/**
 * @brief Encoder motor sets PID control target speed
 * @param rps target speed, in revolutions per second
 * @retval None.
*/
void encoder_motor_set_speed(EncoderMotorObjectTypeDef *self, float rps);

#endif

